### ISSUE TITLE
Update 'Upload Artifacts' step to use correct directory

### ISSUE THREAD

**Issue by realJoshByrnes** [ircclient-dev/irc-dll-template-rs#6]
### Description
After fixing issue #5, we are no longer uploading artifacts due to the fact we have moved the files to the "artifacts" folder. We should ensure that "Upload Artifacts" uses the correct directory.

### Suggested Solution
Update the 'Upload Artifacts' step to:
```yaml
- name: Upload artifacts
  uses: actions/upload-artifact@v4
  with:
    name: ${{ matrix.config.target }}
    path: artifacts/*_${{ matrix.config.extension }}.dll
```

### Acceptance Criteria
- The 'Upload Artifacts' step in the GitHub Actions workflow is updated to use the correct directory.
- Artifacts are successfully uploaded to the correct location after the workflow runs.

### Additional Information
Reference to the current workflow file: [build.yml](https://github.com/ircclient-dev/irc-dll-template-rs/blob/main/.github/workflows/build.yml)
